from resources.BookingResource import BookingResource
from resources.BookingsResource import BookingsResource
from resources.DbResource import DbResource
from resources.LoginResource import LoginResource
from resources.SignUpResource import SignUpResource
from resources.RoomResource import RoomResource
from resources.RoomsAvailableResource import RoomsAvailableResource