services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata: