services:
  web:
    build: .
    ports:
      - "5001:5001"
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata: